# Generated by Django 4.1.2 on 2022-10-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_products_verified_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='verified_product',
            new_name='verified_products',
        ),
    ]
