# Generated by Django 4.1.2 on 2022-10-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='artist',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='size',
            name='length',
        ),
    ]
